spring.application.name=uporabniki

server.port=8002

spring.data.mongodb.host=users-db
spring.data.mongodb.port=27017
spring.data.mongodb.database=usersdb

spring.activemq.broker-url=tcp://activemq:61616
spring.activemq.user=admin
spring.activemq.password=admin

springdoc.api-docs.path=/api/openapi
springdoc.swagger-ui.path=/api/docs