services:
  inventory-db:
    image: postgres:15.17
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data

  inventory-service:
    build: .
    container_name: inventory-service
    depends_on:
      - inventory-db
    environment:
      PORT: 8000
      DB_HOST: inventory-db
      DB_PORT: 5432
      DB_NAME: inventorydb
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"

volumes:
  inventory_postgres_data:
