# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItemAvailability = channel.unary_unary(
                '/inventory.InventoryGrpcService/GetItemAvailability',
                request_serializer=inventory__pb2.ItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.ItemAvailabilityResponse.FromString,
                _registered_method=True)
        self.ReserveItem = channel.unary_unary(
                '/inventory.InventoryGrpcService/ReserveItem',
                request_serializer=inventory__pb2.ReserveItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.ReserveItemResponse.FromString,
                _registered_method=True)
        self.ReturnItem = channel.unary_unary(
                '/inventory.InventoryGrpcService/ReturnItem',
                request_serializer=inventory__pb2.ReturnItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.ReturnItemResponse.FromString,
                _registered_method=True)


class InventoryGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetItemAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItemAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemAvailability,
                    request_deserializer=inventory__pb2.ItemRequest.FromString,
                    response_serializer=inventory__pb2.ItemAvailabilityResponse.SerializeToString,
            ),
            'ReserveItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveItem,
                    request_deserializer=inventory__pb2.ReserveItemRequest.FromString,
                    response_serializer=inventory__pb2.ReserveItemResponse.SerializeToString,
            ),
            'ReturnItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnItem,
                    request_deserializer=inventory__pb2.ReturnItemRequest.FromString,
                    response_serializer=inventory__pb2.ReturnItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.InventoryGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetItemAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryGrpcService/GetItemAvailability',
            inventory__pb2.ItemRequest.SerializeToString,
            inventory__pb2.ItemAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryGrpcService/ReserveItem',
            inventory__pb2.ReserveItemRequest.SerializeToString,
            inventory__pb2.ReserveItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryGrpcService/ReturnItem',
            inventory__pb2.ReturnItemRequest.SerializeToString,
            inventory__pb2.ReturnItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
