# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"\x1e\n\x0bItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\"W\n\x18ItemAvailabilityResponse\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x1a\n\x12\x61vailable_quantity\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\"7\n\x12ReserveItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"7\n\x13ReserveItemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"6\n\x11ReturnItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"6\n\x12ReturnItemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x83\x02\n\x14InventoryGrpcService\x12R\n\x13GetItemAvailability\x12\x16.inventory.ItemRequest\x1a#.inventory.ItemAvailabilityResponse\x12L\n\x0bReserveItem\x12\x1d.inventory.ReserveItemRequest\x1a\x1e.inventory.ReserveItemResponse\x12I\n\nReturnItem\x12\x1c.inventory.ReturnItemRequest\x1a\x1d.inventory.ReturnItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMREQUEST']._serialized_start=30
  _globals['_ITEMREQUEST']._serialized_end=60
  _globals['_ITEMAVAILABILITYRESPONSE']._serialized_start=62
  _globals['_ITEMAVAILABILITYRESPONSE']._serialized_end=149
  _globals['_RESERVEITEMREQUEST']._serialized_start=151
  _globals['_RESERVEITEMREQUEST']._serialized_end=206
  _globals['_RESERVEITEMRESPONSE']._serialized_start=208
  _globals['_RESERVEITEMRESPONSE']._serialized_end=263
  _globals['_RETURNITEMREQUEST']._serialized_start=265
  _globals['_RETURNITEMREQUEST']._serialized_end=319
  _globals['_RETURNITEMRESPONSE']._serialized_start=321
  _globals['_RETURNITEMRESPONSE']._serialized_end=375
  _globals['_INVENTORYGRPCSERVICE']._serialized_start=378
  _globals['_INVENTORYGRPCSERVICE']._serialized_end=637
# @@protoc_insertion_point(module_scope)
