syntax = "proto3";

package inventory;

service InventoryGrpcService {
  rpc GetItemAvailability (ItemRequest) returns (ItemAvailabilityResponse);
  rpc ReserveItem (ReserveItemRequest) returns (ReserveItemResponse);
}

message ItemRequest {
  int32 item_id = 1;
}

message ItemAvailabilityResponse {
  int32 item_id = 1;
  int32 available_quantity = 2;
  string status = 3;
}

message ReserveItemRequest {
  int32 item_id = 1;
  int32 quantity = 2;
}

message ReserveItemResponse {
  bool success = 1;
  string message = 2;
}