name: Micro Frontends CI

on:
  push:
    paths:
      - "web-ui/**"
      - "inventory-ui/**"
      - "reservations-ui/**"
      - "users-ui/**"
      - ".github/workflows/microfrontends-ci.yml"
  pull_request:
    paths:
      - "web-ui/**"
      - "inventory-ui/**"
      - "reservations-ui/**"
      - "users-ui/**"
      - ".github/workflows/microfrontends-ci.yml"

jobs:
  build-frontends:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - web-ui
          - inventory-ui
          - reservations-ui
          - users-ui

    defaults:
      run:
        working-directory: ${{ matrix.app }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build micro frontend
        run: npm run build
